name: musiek audio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.30338
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.1875
  lightness: 0.3301823972724378
  saturation: 0.2293728794902563
  rhythmicContrast: 0.37222257093526423
purpose: []
