name: musiek audio
favicon: null
layout_spectrum: 0.499
typography_spectrum: 0.61278
title: MUSIEK REEL
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010103'
    - '#f7f7f7'
    - '#474548'
    - '#c6c6c6'
    - '#a3a3a3'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
