name: musiek audio
favicon: null
layout_spectrum: 0.74251
typography_spectrum: 0.61278
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010103'
    - '#f7f7f7'
    - '#474548'
    - '#c6c6c6'
    - '#a3a3a3'
  brandStrength: 0.1875
  lightness: 0.3301823972724378
  saturation: 0.2293728794902563
  rhythmicContrast: 0.37222257093526423
purpose: []
